### ISSUE TITLE
Messages aren't being sent from Matrix to Facebook

### ISSUE THREAD

**Issue by tfreedman** [kfatehi/matrix-appservice-facebook#3] opened 2017-01-18 05:25 UTC
If a friend messages me, I'll receive their message from within Matrix. However, if I type anything back to them from within Matrix, they won't get it (and I won't see it on my end from within Facebook Messenger).

However, anything I send from Facebook Messenger itself will be shown in Matrix properly.

**Comment by kfatehi** [comment] 2017-01-20 17:42
The only time I've seen this happen is when, in matrix, your friend's ghost/bot user has not joined the room yet. But if your friend messaged you then the ghost is created in the room, so that cannot be the issue.

Maybe the regex in the registration.yaml is not correct? I believe that is what's used for the HS to know which AS should be forwarded which messages.

**Comment by kfatehi** [comment] 2017-01-20 17:43
A third possibility (and this has happened to me) could be an error in the facebook-chat-api client library which requires it to be re-initialized, although if this was the problem you would see errors in your logs, so it's probably not that.

**Comment by kfatehi** [comment] 2017-01-20 19:04
Another (most likely) possibility is that synapse cannot make any requests to the bridge (networking/setup issue).

**Comment by kfatehi** [comment] 2017-01-20 23:35
Closing this after working with OP and discovering it's not a bug with the bridge ( happy to keep troubleshooting, although I am out of ideas for now). The suspicion at this time is that OP's synapse server cannot make requests to the bridge for some reason.

**Closed by kfatehi** 2017-01-20 23:35 UTC

**Comment by tfreedman** [comment] 2017-01-21 01:08
I can confirm that this isn't a bug with the appservice - turns out I used my domain name in the registration file, as opposed to localhost, so this was a port forwarding issue.

Maybe better error handling should be implemented, but this isn't presently a bug.
